// <auto-generated />
namespace ERPDAL.ConfigurationContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Configuration_tblFaultServiceAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuration_tblFaultServiceAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202007040639272_Configuration_tblFault&ServiceAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
