// <auto-generated />
namespace ERPDAL.InventoryContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inventory_add_prp_tblWarehouseStockInfo_Detail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inventory_add_prp_tblWarehouseStockInfo_Detail));
        
        string IMigrationMetadata.Id
        {
            get { return "202112010747299_Inventory_add_prp_tblWarehouseStockInfo_Detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
