// <auto-generated />
namespace ERPDAL.ProductionContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Production_AssemblyLineInQRCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Production_AssemblyLineInQRCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202006290202402_Production_AssemblyLineInQRCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
