// <auto-generated />
namespace ERPDAL.ProductionContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Production_QRCodeTrace_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Production_QRCodeTrace_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202007260410366_Production_QRCodeTrace_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
