// <auto-generated />
namespace ERPDAL.ProductionContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Production_SubQC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Production_SubQC));
        
        string IMigrationMetadata.Id
        {
            get { return "202110030638252_Production_SubQC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
