// <auto-generated />
namespace ERPDAL.AccountsContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Accounts_tblFinance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accounts_tblFinance));
        
        string IMigrationMetadata.Id
        {
            get { return "202011210557038_Accounts_tblFinance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
