// <auto-generated />
namespace ERPDAL.FrontDeskContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FrontDesk_edit_dataType_tblInvoiceDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FrontDesk_edit_dataType_tblInvoiceDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202012081117380_FrontDesk_edit_dataType_tblInvoiceDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
