// <auto-generated />
namespace ERPDAL.FrontDeskContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FrontDesk_Requsition_IssueQty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FrontDesk_Requsition_IssueQty));
        
        string IMigrationMetadata.Id
        {
            get { return "202111300743527_FrontDesk_Requsition_IssueQty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
